<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression

from scipy import stats

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [2]:
# Read CSV
house_csv = r"C:\Users\OmarZazou\OneDrive - Ediom Pty Ltd\Documents\Resources\Data Science Course\Course Material\DATA\Sacramento_transactions.csv"

In [3]:
house = pd.read_csv(house_csv)

In [4]:
house.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

In [5]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 985 entries, 0 to 984
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   street     985 non-null    object 
 1   city       985 non-null    object 
 2   zip        985 non-null    int64  
 3   state      985 non-null    object 
 4   beds       985 non-null    int64  
 5   baths      985 non-null    int64  
 6   sq__ft     985 non-null    int64  
 7   type       985 non-null    object 
 8   sale_date  985 non-null    object 
 9   price      985 non-null    int64  
 10  latitude   985 non-null    float64
 11  longitude  985 non-null    float64
dtypes: float64(2), int64(5), object(5)
memory usage: 92.5+ KB


### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

# ANSWER
The Target Variable is the price.

#### 2.2 List all possible variables which might be Independent/Predictor variable.

# ANSWER
Beds, Baths, sq_ft would be the best predictors of price

#### 2.3 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [6]:
# ANSWER
house.corr(numeric_only = True)

zip      beds     baths    sq__ft     price  latitude  \
zip        1.000000  0.125319  0.069165  0.130108 -0.093353 -0.290389   
beds       0.125319  1.000000  0.839650  0.684041  0.342024 -0.291307   
baths      0.069165  0.839650  1.000000  0.665690  0.416208 -0.235792   
sq__ft     0.130108  0.684041  0.665690  1.000000  0.333897 -0.383274   
price     -0.093353  0.342024  0.416208  0.333897  1.000000 -0.039573   
latitude  -0.290389 -0.291307 -0.235792 -0.383274 -0.039573  1.000000   
longitude -0.539904 -0.053993  0.016582 -0.177742  0.284485  0.387925   

           longitude  
zip        -0.539904  
beds       -0.053993  
baths       0.016582  
sq__ft     -0.177742  
price       0.284485  
latitude    0.387925  
longitude   1.000000

It would appear here that the predictor variables can be listed based on the correlation coefficients as follows
1- baths
2- beds
3- sq_ft

This is counter-intuitive and I have explored in lab 4.1.1 why this is not accurate because we had many 0 values in the sq_ft (size) column which was causing the correlation to be misrepresneted. When I dropped the objects which had 0 sq_ft the correlation coefficients shifted in favour of the size column.

#### 2.4 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

from sklearn.linear_model import LinearRegression

##### 2.4.1 Fit predictor and target variables using linear regression 

In [7]:
# ANSWER

X_initial = house['sq__ft'].values.reshape(-1,1)
Y_initial = house['price']

In [8]:
linreg = LinearRegression()
linreg.fit(X_initial,Y_initial)

LinearRegression()

Use the print statement below to find the coefficient (Beta_1) and Intercept (Beta_0)

In [9]:
print(linreg.coef_, linreg.intercept_)

[54.15863969] 162930.16140699777


Use the .predict method to find predictions using the regression model.

In [10]:
z = [[15000]]
linreg.predict(z)

array([975309.75673496])

##### 2.4.2 Find R Score

Find $R^2$ Using ```score``` method of Linear Regression.

Use the .score method to find the R_squared value.

In [11]:
# ANSWER
linreg.score(X_initial,Y_initial)

0.11148717682951459

### 3. Splitting Data

In [12]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [13]:
# ANSWER
## Create training and testing subsets
X = house[['sq__ft', 'beds', 'baths']]
Y = house['price']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=42)

linreg = LinearRegression()
linreg.fit(X_train,Y_train)

LinearRegression()

In [14]:
print(linreg.coef_, linreg.intercept_)

[ 5.20978759e+00 -7.63767074e+03  7.66936470e+04] 110671.39825040693


#### 3.2 Check Shape, Sample of Test Train Data

In [15]:
# ANSWER
## Check training/test data
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(788, 3)
(197, 3)
(788,)
(197,)


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [16]:
linreg.score(X_test, Y_test)

0.06654019203017225

This is a very bad r-squared score (a value close to 1 is good whie a value close to 0 is considered poor, we generally assume a 0.7 score or above means good correlation and that the model is a good predictor of prices). This model is weak and we need to improve it.

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [17]:
a = [[15000, 1, 2]]
linreg.predict(a)

C:\Users\OmarZazou\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([334567.83542231])

#### Find the error

In [18]:
# Predict price from X_test
Y_pred = linreg.predict(X_test)

In [19]:
from sklearn.metrics import mean_squared_error

In [20]:
mse = mean_squared_error(Y_test, Y_pred, squared=True)
mse

19181563492.942894

In [21]:
e = np.sqrt(mse)
e

138497.52161299816



---



---



> > > > > > > > > © 2023 Institute of Data


---



---



